### ISSUE TITLE
Isn't this a built in game feature?

### ISSUE THREAD

**Issue by rsValliance** [Daylend/disable-adviser#1]
![image](https://user-images.githubusercontent.com/3433195/227483748-113c574c-e897-405f-8344-73742731012e.png)

This is available in the game settings. Is the purpose of this plugin just to temporary hide it while in combat and then re-enable it?

**Comment by Daylend** [comment]
> Is the purpose of this plugin just to temporary hide it while in combat and then re-enable it?

Yes!

At the time I didn't know about the "Show Activity Adviser" setting, but I decided to publish it anyway since there might be people who enjoy the adviser but don't want it to grief them during combat.
